baseURL = 'https://d-rens.xyz/'
languageCode = 'en-us'
title = "daniels webpage"
theme = "rework"
paginate=5

[params]
  mode="auto"
  subtitle="Hello there, I'm daniel, have a look around"
  # "relatedtext" is the text that appears above the tag list at the bottom of pages.
  relatedtext = "Related"
  # favicon = "/favicon.ico"

  #list items
  datesinlist = true
  authorsinlist = true

  #footer items
  nextprev = true
  taglist = true
  showrss = true


[[menu.main]]
name = "blog"
url = "/blog"
weight = 3

[[menu.main]]
name = "books"
url = "/books"
weigth = 1

[[menu.main]]
name = "about"
url = "/about"
weight = 3

[[menu.main]]
name = "programs"
url = "/programs"


#[params.about]
#title = "~/d-rens"


[[params.social]]
name = "gpg"
icon = "gpg"
url = "https://d-rens.xyz/d-rens.asc"

[[params.social]]
name = "GitHub"
icon = "git"
url = "https://github.com/d-rens"

[[params.social]]
name = "mail"
icon = "mail"
url = "/about#contact"

[[params.social]]
name = "rss"
icon = "rss"
url = "https://d-rens.xyz/index.xml"
