baseURL = 'https://d-rens.xyz/'
languageCode = 'en-us'
title = "daniels webpage"
theme = "risotto-mod"
paginate=5

[params]
  mode="auto"
  subtitle="Hello there, I'm daniel, have a look around"
  # "relatedtext" is the text that appears above the tag list at the bottom of pages.
  relatedtext = "Related"
  # favicon = "/favicon.ico"

  #list items
  datesinlist = true
  authorsinlist = true

  #footer items
  nextprev = true
  taglist = true
  showrss = true

[params.theme]
# palette = "windows-95"

[[menu.main]]
name = "blog"
url = "/blog"
weight = 3

[[menu.main]]
name = "books"
url = "/books"
weigth = 1

[[menu.main]]
name = "about"
url = "/about"
weight = 3

[[menu.main]]
name = "programs"
url = "/programs"


[params.about]
title = "~/d-rens"


[[params.socialLinks]]
icon = "fa-brands fa-github"
title = "GitHub"
url = "https://github.com/d-rens"

[[params.socialLinks]]
icon = "fa-solid fa-envelope"
title = "Email"
url = "/about#contact"

[[params.socialLinks]]
name = "gpg"
icon = "fa-solid fa-lock"
url = "https://d-rens.xyz/d-rens.asc"

[[params.socialLinks]]
name = "rss"
icon = "fa-solid fa-rss"
url = "https://d-rens.xyz/index.xml"



[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/d-rens"

[[params.social]]
name = "mail"
icon = "mail"
url = "/about#contact"

[[params.social]]
name = "rss"
icon = "rss"
url = "https://d-rens.xyz/index.xml"
